# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: falcaopetri
email: falcaopetri@gmail.com
description: > 
        Este é meu tão sonhado espaço para compartilhar conhecimentos.
        Que o conteúdo desse blog seja útil para você, assim como o compromisso de mantê-lo atualizado será para mim.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://falcaopetri.github.io" # the base hostname & protocol for your site
twitter_username: falcaopetri
github_username:  falcaopetri

# Build settings
markdown: kramdown
